Algoritmo "VetorNúmerico"
//Autoria: Jhonata Medeiros Moreira
//Data atual: 20/05/2026
//Objetivo: Preencher um vetor númerico com 8 posições
Var
   numero: Vetor[0..7] de Inteiro
   Contador: Inteiro
Inicio

   Para Contador de 0 até 7 faça
      numero[Contador] <- 999
   fimPara

   Para Contador <- 0 até 7 faça
      Escreva ("[",numero[Contador], " ]")
   Fimpara

   Escreval(" ")

   Para Contador <- 1 até 8 faça
      Escreva ("  ",Contador, "   ")
   Fimpara

Fimalgoritmo