Algoritmo "RepetidaMensagemProcedimento"
//Autoria: Jhonata Medeiros Moreira
//Data atual: 01/06/2026
//Objetivo: Escrever uma mensagem quatro vezes usando procedimento
Var

procedimento Gerador(msg: Caractere; quantidade: Inteiro)
Var
   Contador: Inteiro
inicio

   Escreval("+-------=======------+")
   para Contador de 1 até quantidade faça
      Escreval(msg)
   fimPara
   Escreval("+-------=======------+")

fimprocedimento

Inicio

   Gerador("Aprendendo Portugol", 4)

Fimalgoritmo