Algoritmo "ContagemAjustada"
//Autoria: Jhonata Medeiros Moreira
//Data atual: 16/05/2026
//Objetivo: Ler um número e contar de 0 até ele
Var
   Contador, numero: Inteiro
Inicio

   Escreva("Digite o número qual deseja que a contagem vá até: ")
   Leia(numero)

   limpaTela

   Escreva("Contagem: ")

   Para Contador de 0 até numero faça
      Escreva(Contador)
      Se Contador < numero então
         Escreva(",")
      FimSe
   fimPara
   Escreval(" FIM!")

Fimalgoritmo